### ISSUE TITLE
AutoLangConfig for Label Doesn't Seem to Work in this Case

### ISSUE THREAD

**Issue by markpbaggett** [iiif-prezi/iiif-prezi3#213]
When using the library, a common pattern is to set an auto language across the manifest so that you don't need to set the language each time.  For instance:

```
config.configs['helpers.auto_fields.AutoLang'].auto_lang = "en"
base_url = "https://iiif.io/api/cookbook/recipe/0001-mvm-image"
manifest = Manifest(id=f"{base_url}/manifest.json", label="Single Image Example")
```

With this, the lang of the label would be 'en'. For some reason, that pattern doesn't work in this case:

```
config.configs['helpers.auto_fields.AutoLang'].auto_lang = "en"
natural_light = ResourceItem(
    id="https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-natural/full/max/0/default.jpg",
    type="Image",
    format="image/jpeg",
    width=2000,
    height=1271,
    label="Natural Light"
)
```

Instead, this results in:

```
Traceback (most recent call last):
  File "/Users/mark.baggett/code/iiif-prezi3/testing3.py", line 14, in <module>
    natural_light = ResourceItem(
        id="https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-natural/full/max/0/default.jpg",
    ...<4 lines>...
        label="Natural Light"
    )
  File "/Users/mark.baggett/code/iiif-prezi3/iiif_prezi3/base.py", line 46, in __init__
    super().__init__(**kw)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mark.baggett/code/iiif-prezi3/venv/lib/python3.13/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for ResourceItem
label -> __root__
  value is not a valid dict (type=type_error.dict)
label -> __root__
  value is not a valid dict (type=type_error.dict)
```

### Expected behaviour:
I expected to be able to set the language for the `ResourceItem` with `config.configs['helpers.auto_fields.AutoLang'].auto_lang = "en"`.

### Observed behaviour:
An error was raised:

```
Traceback (most recent call last):
  File "/Users/mark.baggett/code/iiif-prezi3/testing3.py", line 14, in <module>
    natural_light = ResourceItem(
        id="https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-natural/full/max/0/default.jpg",
    ...<4 lines>...
        label="Natural Light"
    )
  File "/Users/mark.baggett/code/iiif-prezi3/iiif_prezi3/base.py", line 46, in __init__
    super().__init__(**kw)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mark.baggett/code/iiif-prezi3/venv/lib/python3.13/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for ResourceItem
label -> __root__
  value is not a valid dict (type=type_error.dict)
label -> __root__
  value is not a valid dict (type=type_error.dict)
```

### Potential bug location(s):
Not sure yet.  I looked in `auto_fields.py`, but I haven't spotted the problem yet.

**Comment by glenrobson** [comment]
As ResourceItem inherites from Base not Class it needs to be added directly here:

https://github.com/iiif-prezi/iiif-prezi3/blob/daf6e8a7ad41773dacb9302358c53e7d09cce58d/iiif_prezi3/helpers/auto_fields.py#L183C1-L183C55

**Comment by markpbaggett** [comment]
[Addressed in 214](https://github.com/iiif-prezi/iiif-prezi3/pull/214/files).
